[allowlist]
  description = "Allow specific test-keys."
  paths = [
  ]
  regexes = [
    '''AKIAIT2Z5TDYPX3ARJBA''',
    '''qR\+vjWPU50fCqQuUWbj9Fain/j2pV\+ZtBCiDiieS''',
    '''fqRvjWaPU5o0fCqQuUWbj9Fainj2pVZtBCiDiieS''',
    '''Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw''',
  ]
