#!/bin/bash -x

/usr/bin/wait_on_postgres.py

# Generating /var/lib/pulp/static at runtime rather than at container build time
# facilitates all of /var/lib/pulp being a separate volume.
django-admin collectstatic --noinput

# Get list of installed plugins via pip
# Assumes they are all named like "pulp-file" -> "file", with no 2nd dash.
PLUGINS=$(pip list | awk -F '[[:space:]]+|[-]' '/pulp-/{printf $2 " " }')
django-admin makemigrations $PLUGINS
django-admin migrate --noinput
django-admin migrate auth --noinput

if [ -n "${PULP_ADMIN_PASSWORD}" ]; then
    django-admin reset-admin-password --password "${PULP_ADMIN_PASSWORD}"
fi

exec gunicorn -b 0.0.0.0:24817 pulpcore.app.wsgi:application
