#!/bin/bash

/usr/bin/wait_on_postgres.py
/usr/bin/wait_on_database_migrations.sh

exec gunicorn pulpcore.content:server \
--bind 0.0.0.0:24816 \
--worker-class 'aiohttp.GunicornWebWorker' \
-w 2 \
--access-logfile -
