# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: telemetry.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftelemetry.proto\"\xcb\x02\n\tTelemetry\x12\x11\n\tsystem_id\x18\x01 \x02(\t\x12\x39\n\x13online_content_apps\x18\x02 \x01(\x0b\x32\x1c.Telemetry.OnlineContentApps\x12\x30\n\x0eonline_workers\x18\x03 \x01(\x0b\x32\x18.Telemetry.OnlineWorkers\x12(\n\ncomponents\x18\x04 \x03(\x0b\x32\x14.Telemetry.Component\x1a\x35\n\x11OnlineContentApps\x12\x11\n\tprocesses\x18\x01 \x01(\r\x12\r\n\x05hosts\x18\x02 \x01(\r\x1a\x31\n\rOnlineWorkers\x12\x11\n\tprocesses\x18\x01 \x01(\r\x12\r\n\x05hosts\x18\x02 \x01(\r\x1a*\n\tComponent\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x0f\n\x07version\x18\x02 \x02(\t')



_TELEMETRY = DESCRIPTOR.message_types_by_name['Telemetry']
_TELEMETRY_ONLINECONTENTAPPS = _TELEMETRY.nested_types_by_name['OnlineContentApps']
_TELEMETRY_ONLINEWORKERS = _TELEMETRY.nested_types_by_name['OnlineWorkers']
_TELEMETRY_COMPONENT = _TELEMETRY.nested_types_by_name['Component']
Telemetry = _reflection.GeneratedProtocolMessageType('Telemetry', (_message.Message,), {

  'OnlineContentApps' : _reflection.GeneratedProtocolMessageType('OnlineContentApps', (_message.Message,), {
    'DESCRIPTOR' : _TELEMETRY_ONLINECONTENTAPPS,
    '__module__' : 'telemetry_pb2'
    # @@protoc_insertion_point(class_scope:Telemetry.OnlineContentApps)
    })
  ,

  'OnlineWorkers' : _reflection.GeneratedProtocolMessageType('OnlineWorkers', (_message.Message,), {
    'DESCRIPTOR' : _TELEMETRY_ONLINEWORKERS,
    '__module__' : 'telemetry_pb2'
    # @@protoc_insertion_point(class_scope:Telemetry.OnlineWorkers)
    })
  ,

  'Component' : _reflection.GeneratedProtocolMessageType('Component', (_message.Message,), {
    'DESCRIPTOR' : _TELEMETRY_COMPONENT,
    '__module__' : 'telemetry_pb2'
    # @@protoc_insertion_point(class_scope:Telemetry.Component)
    })
  ,
  'DESCRIPTOR' : _TELEMETRY,
  '__module__' : 'telemetry_pb2'
  # @@protoc_insertion_point(class_scope:Telemetry)
  })
_sym_db.RegisterMessage(Telemetry)
_sym_db.RegisterMessage(Telemetry.OnlineContentApps)
_sym_db.RegisterMessage(Telemetry.OnlineWorkers)
_sym_db.RegisterMessage(Telemetry.Component)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TELEMETRY._serialized_start=20
  _TELEMETRY._serialized_end=351
  _TELEMETRY_ONLINECONTENTAPPS._serialized_start=203
  _TELEMETRY_ONLINECONTENTAPPS._serialized_end=256
  _TELEMETRY_ONLINEWORKERS._serialized_start=258
  _TELEMETRY_ONLINEWORKERS._serialized_end=307
  _TELEMETRY_COMPONENT._serialized_start=309
  _TELEMETRY_COMPONENT._serialized_end=351
# @@protoc_insertion_point(module_scope)
