#!/usr/bin/env bash

# WARNING: DO NOT EDIT!
#
# This file was generated by plugin_template, and is managed by it. Please use
# './plugin-template --github pulpcore' to update this file.
#
# For more info visit https://github.com/pulp/plugin_template

# This script dumps some files to help understand the setup of the test scenario.

set -eu -o pipefail

# make sure this script runs at the repo root
cd "$(dirname "$(realpath -e "$0")")"/../../..

source .github/workflows/scripts/utils.sh

if [[ -f .github/workflows/scripts/pre_before_script.sh ]]; then
  source .github/workflows/scripts/pre_before_script.sh
fi

# Developers often want to know the final pulp config
echo
echo "# Pulp config:"
tail -v -n +1 .ci/ansible/settings/settings.* ~/.config/pulp_smash/settings.json

echo
echo "# Containerfile:"
tail -v -n +1 .ci/ansible/Containerfile

echo
echo "# Constraints Files:"
# They need not even exist.
tail -v -n +1  ../*/*constraints.txt || true

echo
echo "# pip list outside the container"
pip list

echo
echo "# pip list inside the container"
cmd_prefix bash -c "pip3 list"

echo
echo "# State of the containers"
docker ps -a

if [[ -f .github/workflows/scripts/post_before_script.sh ]]; then
  source .github/workflows/scripts/post_before_script.sh
fi

