#!/usr/bin/env bash

# WARNING: DO NOT EDIT!
#
# This file was generated by plugin_template, and is managed by it. Please use
# './plugin-template --github pulpcore' to update this file.
#
# For more info visit https://github.com/pulp/plugin_template

# This script prepares the scenario definition in the .ci/ansible/vars/main.yaml file.
#
#   It requires the following environment:
#     TEST - The name of the scenario to prepare.
#
#   It may also dump the {lower,upper}bounds_constraints.txt for the specific scenario.

set -eu -o pipefail

# make sure this script runs at the repo root
cd "$(dirname "$(realpath -e "$0")")"/../../..

if [ -f .github/workflows/scripts/pre_before_install.sh ]; then
  source .github/workflows/scripts/pre_before_install.sh
fi

COMPONENT_VERSION="$(bump-my-version show current_version | tail -n -1 | python -c 'from packaging.version import Version; print(Version(input()))')"
COMPONENT_SOURCE="./pulpcore/dist/pulpcore-${COMPONENT_VERSION}-py3-none-any.whl"
if [ "$TEST" = "s3" ]; then
  COMPONENT_SOURCE="${COMPONENT_SOURCE}[s3]"
fi
if [ "$TEST" = "azure" ]; then
  COMPONENT_SOURCE="${COMPONENT_SOURCE}[azure]"
fi

if [[ "$TEST" = "pulp" ]]; then
  python3 .ci/scripts/calc_constraints.py -u requirements.txt > upperbounds_constraints.txt
fi
if [[ "$TEST" = "lowerbounds" ]]; then
  python3 .ci/scripts/calc_constraints.py requirements.txt > lowerbounds_constraints.txt
fi
export PULP_API_ROOT=$(test "${TEST}" = "s3" && echo "/rerouted/djnd/" || echo "/pulp/")

echo "PULP_API_ROOT=${PULP_API_ROOT}" >> "$GITHUB_ENV"

# Compose the scenario definition.
mkdir -p .ci/ansible/vars

cat > .ci/ansible/vars/main.yaml << VARSYAML
---
scenario: "${TEST}"
legacy_component_name: "pulpcore"
component_name: "core"
component_version: "${COMPONENT_VERSION}"
pulp_env: {"PULP_CA_BUNDLE": "/etc/pulp/certs/pulp_webserver.crt"}
pulp_settings: {"allowed_export_paths": ["/tmp"], "allowed_import_paths": ["/tmp"], "orphan_protection_time": 0}
pulp_scheme: "https"
pulp_default_container: "ghcr.io/pulp/pulp-ci-centos:latest"
api_root: "${PULP_API_ROOT}"
image:
  name: "pulp"
  tag: "ci_build"
plugins:
  - name: "pulpcore"
    source: "${COMPONENT_SOURCE}"
    ci_requirements: $(test -f ci_requirements.txt && echo -n true || echo -n false)
    upperbounds: $(test "${TEST}" = "pulp" && echo -n true || echo -n false)
    lowerounds: $(test "${TEST}" = "lowerbounds" && echo -n true || echo -n false)
services:
  - name: "pulp"
    image: "pulp:ci_build"
    volumes:
      - "./settings:/etc/pulp"
      - "./ssh:/keys/"
      - "~/.config:/var/lib/pulp/.config"
      - "../../../pulp-openapi-generator:/root/pulp-openapi-generator"
    env:
      PULP_WORKERS: "4"
      PULP_HTTPS: "true"
  - name: "pulp-fixtures"
    image: "docker.io/pulp/pulp-fixtures:latest"
    env:
      BASE_URL: "http://pulp-fixtures:8080"
VARSYAML

if [ "$TEST" = "s3" ]; then
  MINIO_ACCESS_KEY=AKIAIT2Z5TDYPX3ARJBA
  MINIO_SECRET_KEY=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
  cat >> .ci/ansible/vars/main.yaml << VARSYAML
  - name: "minio"
    image: "minio/minio"
    env:
      MINIO_ACCESS_KEY: "${MINIO_ACCESS_KEY}"
      MINIO_SECRET_KEY: "${MINIO_SECRET_KEY}"
    command: "server /data"
s3_test: true
minio_access_key: "${MINIO_ACCESS_KEY}"
minio_secret_key: "${MINIO_SECRET_KEY}"
pulp_scenario_settings: {"AWS_ACCESS_KEY_ID": "AKIAIT2Z5TDYPX3ARJBA", "AWS_DEFAULT_ACL": "@none None", "AWS_S3_ADDRESSING_STYLE": "path", "AWS_S3_ENDPOINT_URL": "http://minio:9000", "AWS_S3_REGION_NAME": "eu-central-1", "AWS_S3_SIGNATURE_VERSION": "s3v4", "AWS_SECRET_ACCESS_KEY": "fqRvjWaPU5o0fCqQuUWbj9Fainj2pVZtBCiDiieS", "AWS_STORAGE_BUCKET_NAME": "pulp3", "DEFAULT_FILE_STORAGE": "storages.backends.s3boto3.S3Boto3Storage", "MEDIA_ROOT": "", "domain_enabled": true, "hide_guarded_distributions": true}
pulp_scenario_env: {}
VARSYAML
fi

if [ "$TEST" = "azure" ]; then
  cat >> .ci/ansible/vars/main.yaml << VARSYAML
  - name: "ci-azurite"
    image: "mcr.microsoft.com/azure-storage/azurite"
    command: "azurite-blob --skipApiVersionCheck --blobHost 0.0.0.0"
azure_test: true
pulp_scenario_settings: {"AZURE_ACCOUNT_KEY": "Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==", "AZURE_ACCOUNT_NAME": "devstoreaccount1", "AZURE_CONNECTION_STRING": "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://ci-azurite:10000/devstoreaccount1;", "AZURE_CONTAINER": "pulp-test", "AZURE_LOCATION": "pulp3", "AZURE_OVERWRITE_FILES": true, "AZURE_URL_EXPIRATION_SECS": 120, "DEFAULT_FILE_STORAGE": "storages.backends.azure_storage.AzureStorage", "MEDIA_ROOT": "", "domain_enabled": true}
pulp_scenario_env: {}
VARSYAML
fi

if [ "$TEST" = "gcp" ]; then
  cat >> .ci/ansible/vars/main.yaml << VARSYAML
  - name: "ci-gcp"
    image: "fsouza/fake-gcs-server"
    volumes:
      - "storage_data:/etc/pulp"
    command: " -scheme http"
gcp_test: true
pulp_scenario_settings: null
pulp_scenario_env: {}
VARSYAML
fi

cat >> .ci/ansible/vars/main.yaml << VARSYAML
...
VARSYAML
cat .ci/ansible/vars/main.yaml

if [ -f .github/workflows/scripts/post_before_install.sh ]; then
  source .github/workflows/scripts/post_before_install.sh
fi
