#!/bin/bash

# This script expects all <app_label>-api.json files to exist in the plugins root directory.
# It produces a <app_label>-ruby-client.tar file in the plugins root directory.

# WARNING: DO NOT EDIT!
#
# This file was generated by plugin_template, and is managed by it. Please use
# './plugin-template --github pulpcore' to update this file.
#
# For more info visit https://github.com/pulp/plugin_template

set -mveuo pipefail

# make sure this script runs at the repo root
cd "$(dirname "$(realpath -e "$0")")"/../../..

pushd ../pulp-openapi-generator
rm -rf "pulpcore-client"

# We need to copy that over to be visible in the container.
#cp "../pulpcore/core-api.json" .
#./gen-client.sh "core-api.json" "core" ruby "pulpcore"

# -------------
# The generator still needs to have it called api.json at this time...
cp "../pulpcore/api.json" .
./gen-client.sh "api.json" "core" ruby "pulpcore"
# -------------

pushd pulpcore-client
gem build pulpcore_client
tar cvf "../../pulpcore/core-ruby-client.tar" "./pulpcore_client-"*".gem"
popd
popd
