#!/bin/bash

# WARNING: DO NOT EDIT!
#
# This file was generated by plugin_template, and is managed by it. Please use
# './plugin-template --github pulpcore' to update this file.
#
# For more info visit https://github.com/pulp/plugin_template

set -mveuo pipefail

# make sure this script runs at the repo root
cd "$(dirname "$(realpath -e "$0")")"/../../..

source .github/workflows/scripts/utils.sh

export PULP_URL="${PULP_URL:-https://pulp}"


REPORTED_STATUS="$(pulp status)"
REPORTED_VERSION="$(echo "$REPORTED_STATUS" | jq --arg plugin "core" -r '.versions[] | select(.component == $plugin) | .version')"
VERSION="$(echo "$REPORTED_VERSION" | python -c 'from packaging.version import Version; print(Version(input()))')"

pushd ../pulp-openapi-generator
rm -rf pulpcore-client
./generate.sh pulpcore ruby "$VERSION"
pushd pulpcore-client
gem build pulpcore_client
gem install --both "./pulpcore_client-$VERSION.gem"
tar cvf ../../pulpcore/core-ruby-client.tar "./pulpcore_client-$VERSION.gem"
popd
rm -rf pulp_file-client
./generate.sh pulp_file ruby "$VERSION"
pushd pulp_file-client
gem build pulp_file_client
gem install --both "./pulp_file_client-$VERSION.gem"
tar cvf ../../pulpcore/file-ruby-client.tar "./pulp_file_client-$VERSION.gem"
popd
popd
