#!/bin/bash

# WARNING: DO NOT EDIT!
#
# This file was generated by plugin_template, and is managed by it. Please use
# './plugin-template --github pulpcore' to update this file.
#
# For more info visit https://github.com/pulp/plugin_template

set -mveuo pipefail

# make sure this script runs at the repo root
cd "$(dirname "$(realpath -e "$0")")"/../../..

source .github/workflows/scripts/utils.sh

export PULP_URL="${PULP_URL:-https://pulp}"

REPORTED_STATUS="$(pulp status)"
REPORTED_VERSION="$(echo "$REPORTED_STATUS" | jq --arg plugin "core" -r '.versions[] | select(.component == $plugin) | .version')"
VERSION="$(echo "$REPORTED_VERSION" | python -c 'from packaging.version import Version; print(Version(input()))')"

pushd ../pulp-openapi-generator
rm -rf pulpcore-client
./generate.sh pulpcore python "$VERSION"
pushd pulpcore-client
python setup.py sdist bdist_wheel --python-tag py3

twine check "dist/pulpcore_client-$VERSION-py3-none-any.whl" || exit 1
twine check "dist/pulpcore-client-$VERSION.tar.gz" || exit 1

cmd_prefix pip3 install "/root/pulp-openapi-generator/pulpcore-client/dist/pulpcore_client-${VERSION}-py3-none-any.whl"
tar cvf ../../pulpcore/core-python-client.tar ./dist

find ./docs/* -exec sed -i 's/Back to README/Back to HOME/g' {} \;
find ./docs/* -exec sed -i 's/README//g' {} \;
cp README.md docs/index.md
sed -i 's/docs\///g' docs/index.md
find ./docs/* -exec sed -i 's/\.md//g' {} \;
tar cvf ../../pulpcore/core-python-client-docs.tar ./docs
popd
rm -rf pulp_file-client
./generate.sh pulp_file python "$VERSION"
pushd pulp_file-client
python setup.py sdist bdist_wheel --python-tag py3

twine check "dist/pulp_file_client-$VERSION-py3-none-any.whl" || exit 1
twine check "dist/pulp_file-client-$VERSION.tar.gz" || exit 1

cmd_prefix pip3 install "/root/pulp-openapi-generator/pulp_file-client/dist/pulp_file_client-${VERSION}-py3-none-any.whl"
tar cvf ../../pulpcore/file-python-client.tar ./dist

find ./docs/* -exec sed -i 's/Back to README/Back to HOME/g' {} \;
find ./docs/* -exec sed -i 's/README//g' {} \;
cp README.md docs/index.md
sed -i 's/docs\///g' docs/index.md
find ./docs/* -exec sed -i 's/\.md//g' {} \;
tar cvf ../../pulpcore/file-python-client-docs.tar ./docs
popd
popd
