#!/usr/bin/env sh

# WARNING: DO NOT EDIT!
#
# This file was generated by plugin_template, and is managed by bootstrap.py. Please use
# bootstrap.py to update this file.
#
# For more info visit https://github.com/pulp/plugin_template

set -euv

export PRE_BEFORE_SCRIPT=$TRAVIS_BUILD_DIR/.travis/pre_before_script.sh
export POST_BEFORE_SCRIPT=$TRAVIS_BUILD_DIR/.travis/post_before_script.sh

if [ -f $PRE_BEFORE_SCRIPT ]; then
    $PRE_BEFORE_SCRIPT
fi


mkdir -p ~/.config/pulp_smash

if [ -f .travis/pulp-smash-config.json ]; then
    sed "s/localhost/$(hostname)/g" .travis/pulp-smash-config.json > ~/.config/pulp_smash/settings.json
else
    sed "s/localhost/$(hostname)/g" ../pulpcore/.travis/pulp-smash-config.json > ~/.config/pulp_smash/settings.json
fi


if [ -f $POST_BEFORE_SCRIPT ]; then
    $POST_BEFORE_SCRIPT
fi
