# Generated by Django 4.2.15 on 2024-10-22 12:40

from django.db import migrations

# Note: This migration was throwing exceptions so all of the fields/etc were removed.
# The table gets deleted later in 0006_delete_filefilesystemexporter.py.


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0003_auto_20191014_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileFileSystemExporter',
            fields=[
            ],
        ),
    ]
