# Generated by Django 2.2.19 on 2021-04-02 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0009_move_data_to_new_master_distribution_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='filerepository',
            name='autopublish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='filerepository',
            name='manifest',
            field=models.TextField(default='PULP_MANIFEST'),
        ),
    ]
