# Generated by Django 3.2.5 on 2021-08-09 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_acs'),
        ('file', '0012_delete_filefilesystemexporter'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileAlternateContentSource',
            fields=[
                ('alternatecontentsource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='file_filealternatecontentsource', serialize=False, to='core.alternatecontentsource')),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
            },
            bases=('core.alternatecontentsource',),
        ),
    ]
