# Generated by Django 3.2.11 on 2022-03-29 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0013_file_acs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filealternatecontentsource',
            options={'default_related_name': '%(app_label)s_%(model_name)s', 'permissions': [('refresh_filealternatecontentsource', 'Can refresh ACS metadata'), ('manage_roles_filealternatecontentsource', 'Can manage roles on file ACS')]},
        ),
        migrations.AlterModelOptions(
            name='filedistribution',
            options={'default_related_name': '%(app_label)s_%(model_name)s', 'permissions': [('manage_roles_filedistribution', 'Can manage roles on file distributions')]},
        ),
        migrations.AlterModelOptions(
            name='filepublication',
            options={'default_related_name': '%(app_label)s_%(model_name)s', 'permissions': [('manage_roles_filepublication', 'Can manage roles on file publications')]},
        ),
        migrations.AlterModelOptions(
            name='fileremote',
            options={'default_related_name': '%(app_label)s_%(model_name)s', 'permissions': [('manage_roles_fileremote', 'Can manage roles on file remotes')]},
        ),
        migrations.AlterModelOptions(
            name='filerepository',
            options={'default_related_name': '%(app_label)s_%(model_name)s', 'permissions': [('sync_filerepository', 'Can start a sync task'), ('modify_filerepository', 'Can modify content of the repository'), ('manage_roles_filerepository', 'Can manage roles on file repositories'), ('repair_filerepository', 'Can repair repository versions')]},
        ),
    ]
