# Generated by Django 3.2.14 on 2022-10-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0014_new_rbac_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filepublication',
            name='manifest',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='filerepository',
            name='manifest',
            field=models.TextField(default='PULP_MANIFEST', null=True),
        ),
    ]
