# Generated by Django 4.2.26 on 2025-11-12 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0017_alter_filealternatecontentsource_alternatecontentsource_ptr_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filecontent',
            options={'default_related_name': '%(app_label)s_%(model_name)s', 'permissions': [('upload_files', 'Can upload File content using synchronous API.')]},
        ),
    ]
