# Generated by Django 5.2.10 on 2026-02-05 19:22

import django.db.models.deletion
import pulpcore.app.models.access_policy
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0145_domainize_import_export'),
        ('file', '0018_alter_filecontent_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileGitRemote',
            fields=[
                ('remote_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.remote')),
                ('git_ref', models.TextField(default='HEAD')),
            ],
            options={
                'permissions': [('manage_roles_filegitremote', 'Can manage roles on file git remotes')],
                'default_related_name': '%(app_label)s_%(model_name)s',
            },
            bases=('core.remote', pulpcore.app.models.access_policy.AutoAddObjPermsMixin),
        ),
    ]
