# Generated by Django 5.2.14 on 2026-09-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file", "0020_filerepository_last_sync_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="filepublication",
            name="sha256sums",
            field=models.TextField(
                choices=[
                    ("disabled", "Do not generate SHA256SUMS files."),
                    (
                        "root",
                        "Generate a single SHA256SUMS at the root of the repository, listing every file by its path relative to the root.",
                    ),
                    (
                        "directory",
                        "Generate a SHA256SUMS in every directory of the repository, each listing every file below it by its path relative to that directory.",
                    ),
                ],
                default="disabled",
            ),
        ),
        migrations.AddField(
            model_name="filerepository",
            name="sha256sums",
            field=models.TextField(
                choices=[
                    ("disabled", "Do not generate SHA256SUMS files."),
                    (
                        "root",
                        "Generate a single SHA256SUMS at the root of the repository, listing every file by its path relative to the root.",
                    ),
                    (
                        "directory",
                        "Generate a SHA256SUMS in every directory of the repository, each listing every file below it by its path relative to that directory.",
                    ),
                ],
                default="disabled",
            ),
        ),
    ]
