# Generated by Django 4.2.1 on 2023-05-11 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certguard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rhsmcertguard',
            name='contentguard_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.contentguard'),
        ),
        migrations.AlterField(
            model_name='x509certguard',
            name='contentguard_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.contentguard'),
        ),
    ]
