# Generated by Django 2.1.7 on 2019-03-13 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_distribution_remote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='job_id',
        ),
    ]
