# Generated by Django 2.2.2 on 2019-06-27 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contentappstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remote',
            name='validate',
        ),
    ]
