# Generated by Django 2.1.7 on 2019-03-14 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_task_job_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distribution',
            options={'default_related_name': '_distributions'},
        ),
        migrations.AlterField(
            model_name='distribution',
            name='content_guard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_distributions', to='core.ContentGuard'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='publication',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_distributions', to='core.Publication'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_distributions', to='core.Publisher'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='remote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_distributions', to='core.Remote'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='repository',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_distributions', to='core.Repository'),
        ),
    ]
