# Generated by Django 2.2.9 on 2020-01-17 11:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20191127_2350'),
    ]

    operations = [
        migrations.CreateModel(
            name='SigningService',
            fields=[
                ('pulp_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pulp_created', models.DateTimeField(auto_now_add=True)),
                ('pulp_last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.TextField(db_index=True, unique=True)),
                ('script', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
