# Generated by Django 2.2.11 on 2020-04-01 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_change_exporter_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='PulpExport',
            fields=[
                ('export_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Export')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.export',),
        ),
        migrations.AlterField(
            model_name='pulpexporter',
            name='last_export',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='core_pulp_exporter', to='core.PulpExport'),
        ),
    ]
