# Generated by Django 2.2.12 on 2020-04-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_export_backend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basedistribution',
            name='pulp_type',
            field=models.TextField(db_index=True, default=None),
        ),
        migrations.AlterField(
            model_name='content',
            name='pulp_type',
            field=models.TextField(db_index=True, default=None),
        ),
        migrations.AlterField(
            model_name='contentguard',
            name='pulp_type',
            field=models.TextField(db_index=True, default=None),
        ),
        migrations.AlterField(
            model_name='exporter',
            name='pulp_type',
            field=models.TextField(db_index=True, default=None),
        ),
        migrations.AlterField(
            model_name='publication',
            name='pulp_type',
            field=models.TextField(db_index=True, default=None),
        ),
        migrations.AlterField(
            model_name='remote',
            name='pulp_type',
            field=models.TextField(db_index=True, default=None),
        ),
        migrations.AlterField(
            model_name='repository',
            name='pulp_type',
            field=models.TextField(db_index=True, default=None),
        ),
    ]
