# Generated by Django 2.2.12 on 2020-04-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_export_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='signingservice',
            name='sha256',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
