# Generated by Django 2.2.19 on 2021-04-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_add_args_and_kwargs_to_tasks_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='_resource_job_id',
            field=models.UUIDField(null=True),
        ),
    ]
