# Generated by Django 2.2.19 on 2021-04-02 18:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_allow_task_resource_job_id_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='new_reserved_resources_record',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
