# Generated by Django 3.2.8 on 2021-11-17 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_move_remote_url_credentials'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='core_signature', serialize=False, to='core.content')),
                ('signature', models.TextField()),
                ('public_key', models.TextField()),
                ('pubkey_fingerprint', models.TextField()),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='core.content')),
                ('signing_service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signatures', to='core.signingservice')),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
                'unique_together': {('content_ptr', 'signature')},
            },
            bases=('core.content',),
        ),
    ]
