# Generated by Django 3.2.10 on 2022-01-25 10:28

from django.db import migrations, models
import django.db.models.deletion
import pulpcore.app.models.publication


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_alter_rbaccontentguard_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentRedirectContentGuard',
            fields=[
                ('contentguard_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='core_contentredirectcontentguard', serialize=False, to='core.contentguard')),
                ('shared_secret', models.BinaryField(default=pulpcore.app.models.publication._gen_secret, max_length=32)),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
            },
            bases=('core.contentguard',),
        ),
    ]
