# Generated by Django 3.2.11 on 2022-01-31 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_contentredirectcontentguard'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesspolicy',
            name='filtering_permissions',
            field=models.JSONField(null=True),
        ),
    ]
