# Generated by Django 3.2.11 on 2022-02-02 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_contentredirectcontentguard'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesspolicy',
            name='scoping_hooks',
            field=models.JSONField(null=True),
        ),
    ]
