# Generated by Django 3.2.11 on 2022-02-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_task_json_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesspolicy',
            name='filtering_permissions',
            field=models.JSONField(null=True),
        ),
    ]
