# Generated by Django 3.2.13 on 2022-05-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_taskschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesspolicy',
            name='queryset_scoping',
            field=models.JSONField(null=True),
        ),
    ]
