# Generated by Django 3.2.11 on 2022-04-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_taskschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesspolicy',
            name='queryset_scoping',
            field=models.BooleanField(default=False),
        ),
    ]
