# Generated by Django 3.2.13 on 2022-06-01 11:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_alter_contentredirectcontentguard_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesspolicy',
            name='viewset_name',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='filesystemexporter',
            name='method',
            field=models.TextField(choices=[('write', 'Export by writing'), ('hardlink', 'Export by hardlinking'), ('symlink', 'Export by symlinking')], default='write'),
        ),
        migrations.AlterField(
            model_name='groupprogressreport',
            name='code',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='grouprole',
            name='object_id',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='label',
            name='key',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='progressreport',
            name='code',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='repositoryversioncontentdetails',
            name='count_type',
            field=models.TextField(choices=[('A', 'added'), ('P', 'present'), ('R', 'removed')]),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.TextField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='logging_cid',
            field=models.TextField(db_index=True, default=''),
        ),
        migrations.AlterField(
            model_name='task',
            name='reserved_resources_record',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='taskschedule',
            name='name',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='taskschedule',
            name='task_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='object_id',
            field=models.TextField(null=True),
        ),
    ]
