# Generated by Django 3.2.13 on 2022-06-19 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_systemid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upload',
            options={'permissions': [('manage_roles_upload', 'Can manage role assignments on upload')]},
        ),
    ]
