# Generated by Django 3.2.13 on 2022-08-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_alter_upload_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositoryversion',
            name='info',
            field=models.JSONField(default=dict),
        ),
    ]
