# Generated by Django 3.2.15 on 2022-08-18 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_add_info_field_repositoryversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositorycontent',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='version_memberships', to='core.content'),
        ),
        migrations.AlterField(
            model_name='repositorycontent',
            name='version_added',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='added_memberships', to='core.repositoryversion'),
        ),
        migrations.AlterField(
            model_name='repositorycontent',
            name='version_removed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='removed_memberships', to='core.repositoryversion'),
        ),
    ]
