# Generated by Django 3.2.15 on 2022-08-31 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_protect_repository_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='remote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.remote'),
        ),
    ]
