# Generated by Django 3.2.15 on 2022-08-25 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_protect_repository_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtifactDistribution',
            fields=[
                ('distribution_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='core_artifactdistribution', serialize=False, to='core.distribution')),
            ],
            options={
                'permissions': [('manage_roles_artifactdistribution', 'Can manage roles on artifact distributions')],
                'default_related_name': '%(app_label)s_%(model_name)s',
            },
            bases=('core.distribution',),
        ),
    ]
