# Generated by Django 3.2.16 on 2022-11-22 19:08

from django.db import migrations


def remove_telemetry_task_schedule(apps, schema_editor):

    old_task_name = "pulpcore.app.tasks.telemetry.post_telemetry"
    TaskSchedule = apps.get_model("core", "TaskSchedule")
    try:
        TaskSchedule.objects.get(task_name=old_task_name).delete()
    except TaskSchedule.DoesNotExist:
        pass

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0096_alter_task_logging_cid'),
    ]

    operations = [
        migrations.RunPython(
            remove_telemetry_task_schedule, reverse_code=migrations.RunPython.noop, elidable=True
        ),
    ]
