# Generated by Django 3.2.16 on 2022-11-28 08:30

import django.contrib.postgres.fields.hstore
from django.db import migrations

import os
from django.contrib.postgres.operations import HStoreExtension
from django.db.models.expressions import OuterRef, RawSQL
from django.apps import apps as global_apps
from pulpcore.app.apps import PulpPluginAppConfig


def copy_labels_up(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    Label = apps.get_model("core", "Label")

    labeled_ctypes = [ContentType.objects.get(pk=pk) for pk in Label.objects.values_list("content_type", flat=True).distinct()]
    labeled_models_ctypes = [(apps.get_model(ctype.app_label, ctype.model), ctype) for ctype in labeled_ctypes]
    for model, ctype in labeled_models_ctypes:
        label_subq = Label.objects.filter(content_type=ctype, object_id=OuterRef("pulp_id")).annotate(label_data=RawSQL("hstore(array_agg(key), array_agg(value))", [])).values("label_data")
        model.objects.update(pulp_labels=label_subq)
        Label.objects.filter(content_type=ctype).delete()

    if Label.objects.count() != 0:
        raise RuntimeError("Not all labels could be migrated properly. Please raise an issue and stand by for further investigation.")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_remove_telemetry_task_schedule'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]
    # Depend on all installed plugins containing migrations to be able to use their models.
    for plugin_config in global_apps.app_configs.values():
        if isinstance(plugin_config, PulpPluginAppConfig) and os.path.exists(plugin_config.path + "/migrations/0001_initial.py"):
            dependencies.append((plugin_config.label, '0001_initial'))

    operations = [
        HStoreExtension(),
        migrations.AddField(
            model_name='distribution',
            name='pulp_labels',
            field=django.contrib.postgres.fields.hstore.HStoreField(default=dict),
        ),
        migrations.AddField(
            model_name='remote',
            name='pulp_labels',
            field=django.contrib.postgres.fields.hstore.HStoreField(default=dict),
        ),
        migrations.AddField(
            model_name='repository',
            name='pulp_labels',
            field=django.contrib.postgres.fields.hstore.HStoreField(default=dict),
        ),
        migrations.RunPython(code=copy_labels_up, reverse_code=migrations.RunPython.noop, elidable=True),
    ]
