# Generated by Django 3.2.16 on 2022-12-07 13:19

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0098_pulp_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentappstatus',
            name='versions',
            field=django.contrib.postgres.fields.hstore.HStoreField(default=dict),
        ),
        migrations.AddField(
            model_name='worker',
            name='versions',
            field=django.contrib.postgres.fields.hstore.HStoreField(default=dict),
        ),
    ]
