# Generated by Django 3.2.15 on 2022-09-06 14:33

from django.db import migrations, models
import pulpcore.app.models.base


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0104_delete_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesspolicy',
            name='pulp_id',
            field=models.UUIDField(default=pulpcore.app.models.base.pulp_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='alternatecontentsource',
            name='pulp_id',
            field=models.UUIDField(default=pulpcore.app.models.base.pulp_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='alternatecontentsourcepath',
            name='pulp_id',
            field=models.UUIDField(default=pulpcore.app.models.base.pulp_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='pulp_id',
            field=models.UUIDField(default=pulpcore.app.models.base.pulp_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='basedistribution',
            name='pulp_id',
            field=models.UUIDField(default=pulpcore.app.models.base.pulp_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='content',
            name='pulp_id',
            field=models.UUIDField(default=pulpcore.app.models.base.pulp_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contentappstatus',
            name='pulp_id',
            field=models.UUIDField(default=pulpcore.app.models.base.pulp_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contentartifact',
            name='pulp_id',
            field=models.UUIDField(default=pulpcore.app.models.base.pulp_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contentguard',
            name='pulp_id',
            field=models.UUIDField(default=pulpcore.app.models.base.pulp_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='createdresource',
            name='pulp_id',
            field=models.UUIDField(default=pulpcore.app.models.base.pulp_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='pulp_id',
            field=models.UUIDField(default=pulpcore.app.models.base.pulp_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='export',
            name='pulp_id',
            field=models.UUIDField(default=pulpcore.app.models.base.pulp_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='exportedresource',
            name='pulp_id',
            field=models.UUIDField(default=pulpcore.app.models.base.pulp_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='exporter',
            name='pulp_id',
            field=models.UUIDField(default=pulpcore.app.models.base.pulp_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='groupprogressreport',
            name='pulp_id',
            field=models.UUIDField(default=pulpcore.app.models.base.pulp_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='grouprole',
            name='pulp_id',
            field=models.UUIDField(default=pulpcore.app.models.base.pulp_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='import',
            name='pulp_id',
            field=models.UUIDField(default=pulpcore.app.models.base.pulp_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='importer',
            name='pulp_id',
            field=models.UUIDField(default=pulpcore.app.models.base.pulp_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='progressreport',
            name='pulp_id',
            field=models.UUIDField(default=pulpcore.app.models.base.pulp_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='publication',
            name='pulp_id',
            field=models.UUIDField(default=pulpcore.app.models.base.pulp_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='publishedartifact',
            name='pulp_id',
            field=models.UUIDField(default=pulpcore.app.models.base.pulp_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pulpimporterrepository',
            name='pulp_id',
            field=models.UUIDField(default=pulpcore.app.models.base.pulp_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pulptemporaryfile',
            name='pulp_id',
            field=models.UUIDField(default=pulpcore.app.models.base.pulp_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='remote',
            name='pulp_id',
            field=models.UUIDField(default=pulpcore.app.models.base.pulp_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='remoteartifact',
            name='pulp_id',
            field=models.UUIDField(default=pulpcore.app.models.base.pulp_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='repository',
            name='pulp_id',
            field=models.UUIDField(default=pulpcore.app.models.base.pulp_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='repositorycontent',
            name='pulp_id',
            field=models.UUIDField(default=pulpcore.app.models.base.pulp_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='repositoryversion',
            name='pulp_id',
            field=models.UUIDField(default=pulpcore.app.models.base.pulp_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='pulp_id',
            field=models.UUIDField(default=pulpcore.app.models.base.pulp_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='signingservice',
            name='pulp_id',
            field=models.UUIDField(default=pulpcore.app.models.base.pulp_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='systemid',
            name='pulp_id',
            field=models.UUIDField(default=pulpcore.app.models.base.pulp_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='pulp_id',
            field=models.UUIDField(default=pulpcore.app.models.base.pulp_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='taskgroup',
            name='pulp_id',
            field=models.UUIDField(default=pulpcore.app.models.base.pulp_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='taskschedule',
            name='pulp_id',
            field=models.UUIDField(default=pulpcore.app.models.base.pulp_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='upload',
            name='pulp_id',
            field=models.UUIDField(default=pulpcore.app.models.base.pulp_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='uploadchunk',
            name='pulp_id',
            field=models.UUIDField(default=pulpcore.app.models.base.pulp_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='pulp_id',
            field=models.UUIDField(default=pulpcore.app.models.base.pulp_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='worker',
            name='pulp_id',
            field=models.UUIDField(default=pulpcore.app.models.base.pulp_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='domain',
            name='pulp_id',
            field=models.UUIDField(default=pulpcore.app.models.base.pulp_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='upstreampulp',
            name='pulp_id',
            field=models.UUIDField(default=pulpcore.app.models.base.pulp_uuid, editable=False, primary_key=True, serialize=False),
        ),
    ]
