# Generated by Django 4.2.1 on 2023-05-29 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0106_alter_artifactdistribution_distribution_ptr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution',
            name='hidden',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
