# Generated by Django 4.2.1 on 2023-06-16 14:46

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0107_distribution_hidden"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="versions",
            field=django.contrib.postgres.fields.hstore.HStoreField(default=dict),
        ),
    ]
