# Generated by Django 4.2.2 on 2023-06-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0108_task_versions'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contentartifact',
            index=models.Index(fields=['relative_path'], name='core_conten_relativ_ca1ae5_idx'),
        ),
    ]
