# Generated by Django 4.2.1 on 2023-08-21 14:37

import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django_lifecycle.mixins
import pulpcore.app.models.base


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0109_contentartifact_relative_path_index"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiAppStatus",
            fields=[
                (
                    "pulp_id",
                    models.UUIDField(
                        default=pulpcore.app.models.base.pulp_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("pulp_created", models.DateTimeField(auto_now_add=True)),
                ("pulp_last_updated", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.TextField(db_index=True, unique=True)),
                ("last_heartbeat", models.DateTimeField(auto_now=True)),
                ("versions", django.contrib.postgres.fields.hstore.HStoreField(default=dict)),
            ],
            options={
                "abstract": False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
