# Generated by Django 4.2.4 on 2023-09-04 11:56

import django.core.serializers.json
from django.db import migrations
import pulpcore.app.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0110_apiappstatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="enc_args",
            field=pulpcore.app.models.fields.EncryptedJSONField(
                encoder=django.core.serializers.json.DjangoJSONEncoder, null=True
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="enc_kwargs",
            field=pulpcore.app.models.fields.EncryptedJSONField(
                encoder=django.core.serializers.json.DjangoJSONEncoder, null=True
            ),
        ),
    ]
