# Generated by Django 4.2.4 on 2023-08-25 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0111_task_enc_args_task_enc_kwargs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upstreampulp',
            options={'permissions': [('replicate_upstreampulp', 'Can start a replication task'), ('manage_roles_upstreampulp', 'Can manage roles on upstream pulps')]},
        ),
    ]
