# Generated by Django 4.2.6 on 2023-10-23 13:07

from django.db import migrations, models
import django.db.models.deletion
import pulpcore.app.models.access_policy


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0112_alter_upstreampulp_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderContentGuard',
            fields=[
                ('contentguard_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.contentguard')),
                ('header_name', models.TextField()),
                ('header_value', models.TextField()),
                ('jq_filter', models.TextField(null=True)),
            ],
            options={
                'permissions': (('manage_roles_headercontentguard', 'Can manage role assignments on header content guard'),),
                'default_related_name': '%(app_label)s_%(model_name)s',
            },
            bases=('core.contentguard', pulpcore.app.models.access_policy.AutoAddObjPermsMixin),
        ),
    ]
