# Generated by Django 4.2.6 on 2023-10-19 14:20

from django.db import migrations, models
import django.db.models.deletion
import pulpcore.app.models.access_policy


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0114_remove_task_args_remove_task_kwargs'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompositeContentGuard',
            fields=[
                ('contentguard_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.contentguard')),
                ('guards', models.ManyToManyField(related_name='+', to='core.contentguard')),
            ],
            options={
                'permissions': (('manage_roles_compositecontentguard', 'Can manage role assignments on Composite content guard'),),
                'default_related_name': '%(app_label)s_%(model_name)s',
            },
            bases=('core.contentguard', pulpcore.app.models.access_policy.AutoAddObjPermsMixin),
        ),
    ]
