# Generated by Django 4.2.7 on 2023-12-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0115_compositecontentguard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remoteartifact',
            name='md5',
            field=models.CharField(db_index=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='remoteartifact',
            name='sha1',
            field=models.CharField(db_index=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='remoteartifact',
            name='sha224',
            field=models.CharField(db_index=True, max_length=56, null=True),
        ),
        migrations.AlterField(
            model_name='remoteartifact',
            name='sha256',
            field=models.CharField(db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='remoteartifact',
            name='sha384',
            field=models.CharField(db_index=True, max_length=96, null=True),
        ),
        migrations.AlterField(
            model_name='remoteartifact',
            name='sha512',
            field=models.CharField(db_index=True, max_length=128, null=True),
        ),
    ]
