# Generated by Django 4.2.10 on 2024-02-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0116_alter_remoteartifact_md5_alter_remoteartifact_sha1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='unblocked_at',
            field=models.DateTimeField(null=True),
        ),
    ]
