# Generated by Django 4.2.11 on 2024-05-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0117_task_unblocked_at"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["unblocked_at"], name="core_task_unblock_2276a4_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["state"], name="core_task_state_61f0ca_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["state", "pulp_created"], name="core_task_state_3742f2_idx"),
        ),
    ]
