# Generated by Django 4.2.10 on 2024-04-24 11:38

from django.db import migrations
from pulpcore.app.serializers.domain import StorageSettingsSerializer
from django.conf import settings


def default_domain_settings(apps, schema_editor):
    Domain = apps.get_model("core", "Domain")
    default_domain = Domain.objects.get(name="default")
    config_settings = StorageSettingsSerializer.get_default_domain_settings(settings)
    default_domain.storage_class = settings.DEFAULT_FILE_STORAGE
    default_domain.storage_settings = config_settings
    default_domain.hide_guarded_distributions = settings.HIDE_GUARDED_DISTRIBUTIONS
    default_domain.redirect_to_object_storage = settings.REDIRECT_TO_OBJECT_STORAGE
    default_domain.save(skip_hooks=True)


def reverse_default_domain_settings(apps, schema_editor):
    Domain = apps.get_model("core", "Domain")
    default_domain = Domain.objects.get(name="default")
    default_domain.storage_settings = {}
    default_domain.save(skip_hooks=True)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0118_task_core_task_unblock_2276a4_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(default_domain_settings, reverse_code=reverse_default_domain_settings),
    ]
