# Generated by Django 4.2.11 on 2024-05-14 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0118_task_core_task_unblock_2276a4_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="grouprole",
            index=models.Index(fields=["object_id"], name="core_groupr_object__250e22_idx"),
        ),
        migrations.AddIndex(
            model_name="userrole",
            index=models.Index(fields=["object_id"], name="core_userro_object__adb04a_idx"),
        ),
    ]
