# Generated by Django 4.2.10 on 2024-05-29 15:29

from django.db import migrations

from pulpcore.migrations import RequireVersion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0119_grouprole_core_groupr_object__250e22_idx_and_more"),
    ]

    operations = [
        # Migrating from >=3.50 (when get_prn is introduced) is ZDU safe
        RequireVersion("core", "3.50.0"),
    ]
