# Generated by Django 4.2.11 on 2024-08-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0121_add_profile_artifacts_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='upstreampulp',
            name='last_replication',
            field=models.DateTimeField(null=True),
        ),
    ]
