# Generated by Django 4.2.16 on 2024-09-09 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0122_record_last_replication_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskschedule',
            name='pulp_domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.domain'),
        ),
        migrations.AddField(
            model_name='taskschedule',
            name='task_args',
            field=models.TextField(null=True),
        ),
    ]
