# Generated by Django 4.2.4 on 2023-10-07 14:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0124_openpgpkeyring_openpgppublickey_openpgpuserid_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="openpgpkeyring",
            options={
                "default_related_name": "%(app_label)s_%(model_name)s",
                "permissions": [
                    ("modify_openpgpkeyring", "Can modify content of the keyring"),
                    ("manage_roles_openpgpkeyring", "Can manage roles on keyrings"),
                    ("repair_openpgpkeyring", "Can repair repository versions"),
                ],
            },
        ),
    ]
