# Generated by Django 4.2.16 on 2024-11-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0125_openpgpdistribution_openpgpkeyring_openpgppublickey_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remoteartifact',
            name='failed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
