# Generated by Django 4.2.6 on 2023-10-13 13:01

from django.db import migrations, models
import django.db.models.deletion
import pulpcore.app.models.access_policy


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0125_alter_openpgpkeyring_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenPGPDistribution',
            fields=[
                ('distribution_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.distribution')),
            ],
            options={
                'permissions': [('manage_roles_openpgpdistribution', 'Can manage roles on gem distributions')],
                'default_related_name': '%(app_label)s_%(model_name)s',
            },
            bases=('core.distribution', pulpcore.app.models.access_policy.AutoAddObjPermsMixin),
        ),
    ]
