# Generated by Django 4.2.16 on 2024-12-05 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0125_openpgpdistribution_openpgpkeyring_openpgppublickey_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BaseDistribution",
        ),
    ]
