# Generated by Django 4.2.16 on 2025-01-28 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0126_remoteartifact_failed_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upstreampulp',
            name='pulp_label_select',
        ),
    ]
