# Generated by Django 4.2.19 on 2025-02-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0127_remove_upstreampulp_pulp_label_select'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution',
            name='checkpoint',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publication',
            name='checkpoint',
            field=models.BooleanField(default=False),
        ),
    ]
