# Generated by Django 4.2.15 on 2024-09-08 23:15

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0128_domain_pulp_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='pulp_labels',
            field=django.contrib.postgres.fields.hstore.HStoreField(default=dict),
        ),
    ]
