# Generated by Django 4.2.16 on 2025-02-18 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0129_content_pulp_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='upstreampulp',
            name='policy',
            field=models.TextField(choices=[('all', 'Replicate manages ALL local objects within the domain.'), ('labeled', 'Replicate will only manage the objects created from a previous replication, unlabled local objects will be untouched.'), ('nodelete', 'Replicate will not delete any local object whether they were created by replication or not.')], default='all'),
        ),
    ]
