# Generated by Django 4.2.20 on 2025-03-07 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0131_distribution_checkpoint_publication_checkpoint"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="content",
            options={
                "permissions": [("manage_content_labels", "Can manage content-labels")],
                "verbose_name_plural": "content",
            },
        ),
    ]
