# Generated by Django 4.2.10 on 2025-06-26 19:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0131_distribution_checkpoint_publication_checkpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='profile_options',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None),
        ),
    ]
