# Generated by Django 4.2.22 on 2025-06-06 14:32

from django.db import migrations

# TODO: We need to think about a ZDU version of this change.


TASK_INSERT_TRIGGER_UP = """
CREATE FUNCTION on_insert_timestamp_task()
  RETURNS TRIGGER
  LANGUAGE plpgsql
  AS $$
    BEGIN
      PERFORM pg_advisory_xact_lock(0, 21);  -- Same as TASK_DISPATCH_LOCK
      NEW.pulp_created = clock_timestamp();
      IF NEW.pulp_created <= (SELECT MAX(pulp_created) FROM core_task)
      THEN
        RAISE EXCEPTION 'Clock screw detected.';
      END IF;
      RETURN NEW;
    END;
  $$
;

CREATE TRIGGER on_insert_timestamp_task_trigger
  BEFORE INSERT
  ON core_task
  FOR EACH ROW
  EXECUTE FUNCTION on_insert_timestamp_task()
;
"""

TASK_INSERT_TRIGGER_DOWN = """
DROP TRIGGER on_insert_timestamp_task_trigger on core_task;
DROP FUNCTION on_insert_timestamp_task;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0131_distribution_checkpoint_publication_checkpoint"),
    ]

    operations = [
        migrations.RunSQL(sql=TASK_INSERT_TRIGGER_UP, reverse_sql=TASK_INSERT_TRIGGER_DOWN),
    ]
