# Generated by Django 4.2.16 on 2025-07-10 14:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0132_task_profile_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="repositoryversion",
            name="content_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.UUIDField(), default=None, null=True, size=None
            ),
        ),
    ]
