# Generated by Django 4.2.16 on 2024-12-05 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0131_distribution_checkpoint_publication_checkpoint"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BaseDistribution",
        ),
    ]
