# Generated by Django 4.2.22 on 2025-07-07 11:07

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0134_task_insert_trigger"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="task",
            index=django.contrib.postgres.indexes.GinIndex(
                condition=models.Q(
                    ("state__in", ["completed", "failed", "canceled", "skipped"]), _negated=True
                ),
                fields=["reserved_resources_record"],
                name="pulp_task_resources_index",
                opclasses=["array_ops"],
            ),
        ),
    ]
