# Generated by Django 4.2.23 on 2025-08-07 08:46

import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django_lifecycle.mixins
import pulpcore.app.models.base


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0136_delete_basedistribution'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppStatus',
            fields=[
                ('pulp_id', models.UUIDField(default=pulpcore.app.models.base.pulp_uuid, editable=False, primary_key=True, serialize=False)),
                ('pulp_created', models.DateTimeField(auto_now_add=True)),
                ('pulp_last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('app_type', models.CharField(choices=[('api', 'api'), ('content', 'content'), ('worker', 'worker')], max_length=10)),
                ('name', models.TextField(db_index=True, unique=True)),
                ('versions', django.contrib.postgres.fields.hstore.HStoreField(default=dict)),
                ('ttl', models.DurationField()),
                ('last_heartbeat', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
