# Generated by Django 4.2.23 on 2025-08-07 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0138_vulnerabilityreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='app_lock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='core.appstatus'),
        ),
    ]
