# Generated by Django 4.2.23 on 2025-08-12 15:20

from django.db import migrations
from pulpcore.migrations import RequireVersion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0139_task_app_lock'),
    ]

    operations = [
        RequireVersion("core", "3.85"),
    ]
