# Generated by Django 4.2.23 on 2025-08-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0140_require_appstatus_zdu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appstatus',
            name='name',
            field=models.TextField(),
        ),
    ]
