# Generated by Django 4.2.24 on 2025-09-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0142_task_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteDownload',
            fields=[
                ('download_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('temp_path', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
