# Generated by Django 4.2.23 on 2025-09-04 08:58

from django.db import migrations
from pulpcore.migrations import RequireVersion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0142_task_result"),
    ]

    operations = [
        RequireVersion("core", "3.87"),
    ]
