# Generated by Django 4.2.23 on 2025-09-09 08:24

from django.db import migrations
from pulpcore.migrations import RequireVersion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0143_require_app_lock_zdu'),
    ]

    operations = [
        RequireVersion("core", "3.87"),
        migrations.DeleteModel(
            name='ApiAppStatus',
        ),
        migrations.DeleteModel(
            name='ContentAppStatus',
        ),
        migrations.RemoveField(
            model_name='task',
            name='worker',
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
