# Generated by Django 4.2.23 on 2025-08-21 21:21

from django.db import migrations, models
import django.db.models.deletion
import pulpcore.app.util


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0144_delete_old_appstatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="export",
            name="pulp_domain",
            field=models.ForeignKey(default=pulpcore.app.util.get_domain_pk, on_delete=django.db.models.deletion.PROTECT, to="core.domain"),
        ),
        migrations.AddField(
            model_name="exporter",
            name="pulp_domain",
            field=models.ForeignKey(default=pulpcore.app.util.get_domain_pk, on_delete=django.db.models.deletion.PROTECT, to="core.domain"),
        ),
        migrations.AlterUniqueTogether(
            name="exporter",
            unique_together={("name", "pulp_domain")},
        ),
        migrations.AddField(
            model_name="import",
            name="pulp_domain",
            field=models.ForeignKey(default=pulpcore.app.util.get_domain_pk, on_delete=django.db.models.deletion.PROTECT, to="core.domain"),
        ),
        migrations.AddField(
            model_name="importer",
            name="pulp_domain",
            field=models.ForeignKey(default=pulpcore.app.util.get_domain_pk, on_delete=django.db.models.deletion.PROTECT, to="core.domain"),
        ),
        migrations.AlterUniqueTogether(
            name="importer",
            unique_together={("name", "pulp_domain")},
        ),
        migrations.AlterField(
            model_name="exporter",
            name="name",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="importer",
            name="name",
            field=models.TextField(),
        ),
    ]
