# Generated by Django 5.2.10 on 2026-03-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0145_domainize_import_export"),
    ]

    operations = [
        migrations.AddField(
            model_name="distribution",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
