# Generated by Django 5.2.7 on 2026-03-17 18:32

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0145_domainize_import_export'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='content',
            index=django.contrib.postgres.indexes.GinIndex(fields=['pulp_labels'], name='pulp_labels_gin_index'),
        ),
    ]
