# Generated by Django 5.2.12 on 2026-03-09 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0145_domainize_import_export"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="retain_checkpoints",
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
