# Generated by Django 5.2.7 on 2026-03-17 18:32

from django.db import migrations
from django.contrib.postgres.indexes import GinIndex
from django.contrib.postgres.operations import AddIndexConcurrently


class Migration(migrations.Migration):
    atomic = False  # required for CONCURRENTLY

    dependencies = [
        ("core", "0146_repository_retain_checkpoints"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="content",
            index=GinIndex(fields=["pulp_labels"], name="pulp_labels_gin_index"),
        ),
    ]
