# Generated by Django 5.2.7 on 2026-03-23 16:34

from django.db import migrations, models
from django.contrib.postgres.operations import AddIndexConcurrently


class Migration(migrations.Migration):
    atomic = False # required for CONCURRENTLY

    dependencies = [
        ("core", "0147_content_pulp_labels_gin"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="artifact",
            index=models.Index(fields=["pulp_domain", "size"], name="artifact_domain_size_index"),
        ),
    ]
