# Generated by Django 5.2.10 on 2026-03-30 18:48

import django.db.models.deletion
import django_lifecycle.mixins
import pulpcore.app.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0148_artifact_artifact_domain_size_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributedPublication',
            fields=[
                ('pulp_id', models.UUIDField(default=pulpcore.app.models.base.pulp_uuid, editable=False, primary_key=True, serialize=False)),
                ('pulp_created', models.DateTimeField(auto_now_add=True)),
                ('pulp_last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('expires_at', models.DateTimeField(null=True)),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_distributedpublications', to='core.distribution')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_distributedpublications', to='core.publication')),
            ],
            options={
                'abstract': False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
