# Generated by Django 5.2.11 on 2026-05-12 03:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0150_taskschedule_task_kwargs'),
    ]

    operations = [
        migrations.AddField(
            model_name='upstreampulp',
            name='connect_timeout',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0, 'Timeout must be >= 0')]),
        ),
        migrations.AddField(
            model_name='upstreampulp',
            name='download_concurrency',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1, 'Download concurrency must be at least 1')]),
        ),
        migrations.AddField(
            model_name='upstreampulp',
            name='max_retries',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='upstreampulp',
            name='sock_connect_timeout',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0, 'Timeout must be >= 0')]),
        ),
        migrations.AddField(
            model_name='upstreampulp',
            name='sock_read_timeout',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0, 'Timeout must be >= 0')]),
        ),
        migrations.AddField(
            model_name='upstreampulp',
            name='total_timeout',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0, 'Timeout must be >= 0')]),
        ),
    ]
