# Generated by Django 5.2.11 on 2026-05-27 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0151_upstreampulp_connect_timeout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternatecontentsource',
            name='remote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.remote'),
        ),
    ]
