# Generated by Django 5.2.13 on 2026-06-08 21:54

import django.contrib.postgres.fields
from django.db import migrations, models, transaction

# Same membership as RepositoryVersion._content_relationships().
_POPULATE_SQL = """
UPDATE __RV__ AS rv
SET content_ids = COALESCE((
    SELECT ARRAY_AGG(rc.content_id)
    FROM __RC__ AS rc
    INNER JOIN __RV__ AS va ON va.pulp_id = rc.version_added_id
    LEFT JOIN __RV__ AS vr ON vr.pulp_id = rc.version_removed_id
    WHERE rc.repository_id = rv.repository_id
      AND va.number <= rv.number
      AND (vr.pulp_id IS NULL OR vr.number > rv.number)
), '{}'::uuid[])
WHERE rv.repository_id = %s
  AND rv.content_ids IS NULL
"""


def populate_content_ids(apps, schema_editor):
    """Fill missing content_ids from content membership, committing per repository."""
    RepositoryVersion = apps.get_model("core", "RepositoryVersion")
    RepositoryContent = apps.get_model("core", "RepositoryContent")
    connection = schema_editor.connection
    qn = schema_editor.quote_name
    rv = qn(RepositoryVersion._meta.db_table)
    rc = qn(RepositoryContent._meta.db_table)
    sql = _POPULATE_SQL.replace("__RV__", rv).replace("__RC__", rc)

    with connection.cursor() as cursor:
        cursor.execute(f"SELECT DISTINCT repository_id FROM {rv} WHERE content_ids IS NULL")
        repo_ids = [row[0] for row in cursor.fetchall()]

    for repo_id in repo_ids:
        with transaction.atomic(using=connection.alias):
            with connection.cursor() as cursor:
                cursor.execute(sql, [repo_id])


class Migration(migrations.Migration):
    # Per-repository commits inside RunPython; AlterField runs afterwards.
    atomic = False

    dependencies = [
        ("core", "0151_upstreampulp_connect_timeout_and_more"),
    ]

    operations = [
        migrations.RunPython(
            populate_content_ids,
            reverse_code=migrations.RunPython.noop,
            elidable=True,
            atomic=False,
        ),
        migrations.AlterField(
            model_name="repositoryversion",
            name="content_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.UUIDField(), default=list, size=None
            ),
        ),
    ]
