# Generated by Django 5.2.13 on 2026-06-08 21:54

import django.contrib.postgres.fields
from django.db import migrations, models


def populate_content_ids(apps, schema_editor):
    RepositoryVersion = apps.get_model('core', 'RepositoryVersion')
    RepositoryContent = apps.get_model('core', 'RepositoryContent')
    repo_versions = []
    for rv in RepositoryVersion.objects.filter(content_ids=None).iterator(chunk_size=2000):
        rv.content_ids = list(RepositoryContent.objects.filter(
            repository_id=rv.repository_id, version_added__number__lte=rv.number
        ).exclude(version_removed__number__lte=rv.number).values_list("content_id", flat=True))
        repo_versions.append(rv)
        if len(repo_versions) >= 2000:
            RepositoryVersion.objects.bulk_update(repo_versions, ['content_ids'])
            repo_versions = []
    if repo_versions:
        RepositoryVersion.objects.bulk_update(repo_versions, ['content_ids'])

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0151_upstreampulp_connect_timeout_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_content_ids, reverse_code=migrations.RunPython.noop, elidable=True),
        migrations.AlterField(
            model_name='repositoryversion',
            name='content_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), default=list, size=None),
        ),
    ]
