# Generated by Django 5.2.14 on 2026-06-01 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0152_alter_repositoryversion_content_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='version',
            field=models.TextField(default='v3'),
        ),
    ]
