# Generated by Django 5.2.13 on 2026-06-30 14:28

import django.db.models.deletion
import pulpcore.app.util
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0152_alter_repositoryversion_content_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskschedule',
            name='pulp_domain',
            field=models.ForeignKey(default=pulpcore.app.util.get_domain_pk, on_delete=django.db.models.deletion.CASCADE, to='core.domain'),
        ),
        migrations.AlterField(
            model_name='taskschedule',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name='taskschedule',
            unique_together={('name', 'pulp_domain')},
        ),
    ]
