# Generated by Django 5.2.14 on 2026-07-10 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0153_taskschedule_pulp_domain_alter_taskschedule_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='pulp_api_version',
            field=models.TextField(default='v3'),
        ),
    ]
