# Generated by Django 5.2.13 on 2026-07-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0153_taskschedule_pulp_domain_alter_taskschedule_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="database_alias",
            field=models.SlugField(
                default="default",
                help_text="DATABASES alias where this domain's data-plane objects reside.",
            ),
        ),
        migrations.AddField(
            model_name="domain",
            name="moving",
            field=models.BooleanField(
                default=False,
                help_text="True while this domain's data is being moved between database "
                "aliases.",
            ),
        ),
    ]
