# Generated by Django 5.2.17 on 2026-08-07 12:29

from django.db import migrations


CREATE_REL_PATH_DOMAINS = r"""
CREATE DOMAIN "relative_path" AS text CHECK ('/' || VALUE || '/' !~ '[\n\r\s\t\?#]|(/\.{0,2}/)');
"""

REMOVE_REL_PATH_DOMAINS = """
DROP DOMAIN IF EXISTS "relative_path";
"""


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0154_task_api_version'),
    ]

    operations = [
        migrations.RunSQL(sql=CREATE_REL_PATH_DOMAINS, reverse_sql=REMOVE_REL_PATH_DOMAINS),
    ]
