# Generated by Django 5.2.14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0154_task_api_version"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="openpgpdistribution",
            options={
                "default_related_name": "%(app_label)s_%(model_name)s",
                "permissions": [
                    (
                        "manage_roles_openpgpdistribution",
                        "Can manage roles on openpgp distributions",
                    )
                ],
            },
        ),
    ]
