# Generated by Django 5.2.15 on 2026-07-09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """KI-18: denormalize the target domain of every GenericForeignKey `content_object`.

    `CreatedResource`/`ExportedResource`/`UserRole`/`GroupRole` are control-plane models
    (always on `default`) whose `content_object` may point at a data-plane object living on a
    satellite alias. See `pulpcore.app.models.generic.DomainResolvedGenericRelation` for why
    this field is required for `content_object` to resolve correctly once a domain has moved
    off `default`.
    """

    dependencies = [
        ("core", "0154_domain_database_alias_domain_moving"),
    ]

    operations = [
        migrations.AddField(
            model_name="createdresource",
            name="content_object_domain",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.domain",
            ),
        ),
        migrations.AddField(
            model_name="exportedresource",
            name="content_object_domain",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.domain",
            ),
        ),
        migrations.AddField(
            model_name="grouprole",
            name="content_object_domain",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.domain",
            ),
        ),
        migrations.AddField(
            model_name="userrole",
            name="content_object_domain",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.domain",
            ),
        ),
    ]
