# Generated by Django 5.2.15 on 2026-07-09

import django_lifecycle.mixins
import pulpcore.app.models.base
from django.db import migrations, models


class Migration(migrations.Migration):
    """phase1-migrate-all: per-alias bookkeeping for the `migrate-all` orchestration command."""

    dependencies = [
        ("core", "0155_createdresource_content_object_domain_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MigrationStatus",
            fields=[
                (
                    "pulp_id",
                    models.UUIDField(
                        default=pulpcore.app.models.base.pulp_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("pulp_created", models.DateTimeField(auto_now_add=True)),
                ("pulp_last_updated", models.DateTimeField(auto_now=True, null=True)),
                ("database_alias", models.TextField(unique=True)),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("complete", "Complete"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                    ),
                ),
                ("completed_at", models.DateTimeField(null=True)),
                ("error", models.TextField(null=True)),
            ],
            options={
                "verbose_name_plural": "migration statuses",
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
