# Generated by Django 5.2.15 on 2026-08-10 10:26 — restructured to avoid deadlocks (issue #8058)

import django.contrib.postgres.indexes
import django.db.models.expressions
import pulpcore.app.models.fields
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations


_CHECK = r"'/' || {col} || '/' !~ '[\n\r\s\t\?#]|(/\.{{0,2}}/)'"


def _add_constraint(table, constraint, col):
    return migrations.RunSQL(
        sql=f"ALTER TABLE {table} ADD CONSTRAINT {constraint} CHECK ({_CHECK.format(col=col)}) NOT VALID;",
        reverse_sql=f"ALTER TABLE {table} DROP CONSTRAINT IF EXISTS {constraint};",
    )


class Migration(migrations.Migration):
    atomic = False  # required for AddIndexConcurrently and NOT VALID constraint adds outside a single transaction

    dependencies = [
        ('core', '0155_create_rel_path_domains'),
    ]

    operations = [
        # core_contentartifact.relative_path
        migrations.SeparateDatabaseAndState(
            database_operations=[
                _add_constraint(
                    "core_contentartifact",
                    "contentartifact_relative_path_domain_check",
                    "relative_path",
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='contentartifact',
                    name='relative_path',
                    field=pulpcore.app.models.fields.RelativePathField(),
                ),
            ],
        ),
        # core_distribution.base_path
        migrations.SeparateDatabaseAndState(
            database_operations=[
                _add_constraint(
                    "core_distribution",
                    "distribution_base_path_domain_check",
                    "base_path",
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='distribution',
                    name='base_path',
                    field=pulpcore.app.models.fields.RelativePathField(),
                ),
            ],
        ),
        # core_publishedartifact.relative_path
        migrations.SeparateDatabaseAndState(
            database_operations=[
                _add_constraint(
                    "core_publishedartifact",
                    "publishedartifact_relative_path_domain_check",
                    "relative_path",
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='publishedartifact',
                    name='relative_path',
                    field=pulpcore.app.models.fields.RelativePathField(),
                ),
            ],
        ),
        # core_publishedmetadata.relative_path
        migrations.SeparateDatabaseAndState(
            database_operations=[
                _add_constraint(
                    "core_publishedmetadata",
                    "publishedmetadata_relative_path_domain_check",
                    "relative_path",
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='publishedmetadata',
                    name='relative_path',
                    field=pulpcore.app.models.fields.RelativePathField(),
                ),
            ],
        ),
        # SpGist index — CONCURRENTLY avoids locking core_distribution
        AddIndexConcurrently(
            model_name='distribution',
            index=django.contrib.postgres.indexes.SpGistIndex(
                django.contrib.postgres.indexes.OpClass("base_path", name='text_ops'),
                include=('pulp_domain',),
                name='core_distribution_base_path_text',
            ),
        ),
    ]
