# Generated by Django 5.2.15 on 2026-08-10 10:26

import django.contrib.postgres.indexes
import django.contrib.postgres.operations
import django.db.models.expressions
import pulpcore.app.models.fields
from django.db import migrations


# Obervations made while fixing this:
#   - "ALTER TABLE ... VALIDATE CONSTRAINT" is idempotent.
#     Even though postgres tracks whether a constraint was created / is still "NOT VALID".
#   - "NOT VALID" cannot be used when changing the type of a column to a domain that adds a check.
#   - Neither "ADD CONSTRAINT" nor "VALIDATE CONSTRAINT" have "IF (NOT) EXISTS" clauses.
#     One can fake "ADD CONSTRAINT IF NOT EXISTS" by a clever combination of create-drop-rename.


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0155_create_rel_path_domains'),
    ]

    # This is needed to allow the concurrent reindex in the end.
    atomic = False

    operations = [
        migrations.AlterField(
            model_name='contentartifact',
            name='relative_path',
            field=django.db.models.fields.TextField(null=True, default=None),
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE "core_contentartifact" ADD CONSTRAINT "temp_relative_path_check" CHECK ('/' || "relative_path" || '/' !~ '[\n\r\s\t\?#]|(/\.{0,2}/)') NOT VALID;
            """,
            reverse_sql="""
            ALTER TABLE "core_contentartifact" DROP CONSTRAINT IF EXISTS "temp_relative_path_check";
            UPDATE "core_contentartifact" SET "relative_path" = '' WHERE "relative_path" is NULL;
            """,
            elidable=True,
        ),

        migrations.RunSQL(
            sql="""
            ALTER TABLE "core_distribution" ADD CONSTRAINT "temp_relative_path_check" CHECK ('/' || "base_path" || '/' !~ '[\n\r\s\t\?#]|(/\.{0,2}/)') NOT VALID;
            """,
            reverse_sql="""
            ALTER TABLE "core_distribution" DROP CONSTRAINT IF EXISTS "temp_relative_path_check";
            """,
            elidable=True,
        ),

        migrations.RunSQL(
            sql="""
            ALTER TABLE "core_publishedartifact" ADD CONSTRAINT "temp_relative_path_check" CHECK ('/' || "relative_path" || '/' !~ '[\n\r\s\t\?#]|(/\.{0,2}/)') NOT VALID;
            """,
            reverse_sql="""
            ALTER TABLE "core_publishedartifact" DROP CONSTRAINT IF EXISTS "temp_relative_path_check";
            """,
        ),

        migrations.RunSQL(
            sql="""
            ALTER TABLE "core_publishedmetadata" ADD CONSTRAINT "temp_relative_path_check" CHECK ('/' || "relative_path" || '/' !~ '[\n\r\s\t\?#]|(/\.{0,2}/)') NOT VALID;
            """,
            reverse_sql="""
            ALTER TABLE "core_publishedmetadata" DROP CONSTRAINT IF EXISTS "temp_relative_path_check";
            """,
        ),

        django.contrib.postgres.operations.AddIndexConcurrently(
            # Moving this to another migration would confuse the timelines again.
            model_name='distribution',
            index=django.contrib.postgres.indexes.SpGistIndex(django.contrib.postgres.indexes.OpClass("base_path", name='text_ops'), include=('pulp_domain',), name='core_distribution_base_path_text'),
        ),
    ]
