# Generated by Django 5.2.15 on 2026-08-10 10:26

import django.contrib.postgres.indexes
import django.contrib.postgres.operations
import django.db.models.expressions
import pulpcore.app.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('core', '0155_create_rel_path_domains'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='base_path',
            field=pulpcore.app.models.fields.RelativePathField(),
        ),
        django.contrib.postgres.operations.AddIndexConcurrently(
            model_name='distribution',
            index=django.contrib.postgres.indexes.SpGistIndex(django.contrib.postgres.indexes.OpClass("base_path", name='text_ops'), include=('pulp_domain',), name='core_distribution_base_path_text'),
        ),
    ]
