# Generated by Django 5.2.17 on 2026-08-11 10:34

from django.db import migrations


ADD_TRIGGER = r"""
CREATE OR REPLACE FUNCTION path_prefixes("path" text)
RETURNS text[] AS $$
DECLARE
        segment text;
        segments text[] := string_to_array(path, '/');
        prefix text := '';
        prefixes text[];
BEGIN
        -- Return directory prefixes of a path.
        -- 'a/b/c' -> {'a', 'a/b'}
        prefix := segments[1];
        FOREACH segment IN ARRAY segments[2:]
        LOOP
                prefixes := prefixes || prefix;
                prefix := prefix || '/' || segment;
        END LOOP;
        RETURN prefixes;
END;
$$ LANGUAGE plpgsql
IMMUTABLE
RETURNS NULL ON NULL INPUT
PARALLEL SAFE;

CREATE OR REPLACE FUNCTION "check_core_distribution_base_path_prefix_free" ()
RETURNS TRIGGER AS $$
DECLARE
        base_path_slash text := new.base_path || '/';
BEGIN
        -- Check that no base_path is a prefix of another.
        -- The normalization of "/" ensures that a simple string comparison actually suffice.
        -- WARNING: This check alone does not ensure uniqueness.

        -- ^@ seems to only use an index when the indexed expression is on the left (pg18).
        PERFORM 1 FROM "core_distribution"
                WHERE
                        "pulp_id" != new."pulp_id"
                        AND
                        "pulp_domain_id" = new."pulp_domain_id"
                        AND
                        "base_path" ^@ base_path_slash
                LIMIT 1;
        IF FOUND THEN
                RAISE EXCEPTION '"%" is the prefix of an existing base_path.', new."base_path"
                    USING ERRCODE = 'exclusion_violation';
        END IF;

        -- This variant however uses the existing uniqueness index.
        PERFORM 1 FROM "core_distribution"
                WHERE
                        "pulp_id" != new."pulp_id"
                        AND
                        "pulp_domain_id" = new."pulp_domain_id"
                        AND
                        "base_path" = ANY(path_prefixes(new."base_path"))
                LIMIT 1;
        IF FOUND THEN
                RAISE EXCEPTION '"%" is prefixed by an existing base_path.', new."base_path"
                    USING ERRCODE = 'exclusion_violation';
        END IF;

        RETURN new;
END
$$ LANGUAGE plpgsql;

CREATE CONSTRAINT TRIGGER "core_distribution_insert_base_path_overlap_constraint"
        AFTER INSERT
        ON "core_distribution"
        DEFERRABLE INITIALLY DEFERRED
        FOR EACH ROW
        WHEN (new."base_path" IS NOT NULL)
        EXECUTE FUNCTION "check_core_distribution_base_path_prefix_free" ();

CREATE CONSTRAINT TRIGGER "core_distribution_update_base_path_overlap_constraint"
        AFTER UPDATE
        ON "core_distribution"
        DEFERRABLE INITIALLY DEFERRED
        FOR EACH ROW
        WHEN (new."base_path" IS NOT NULL AND new."base_path" != old."base_path")
        EXECUTE FUNCTION "check_core_distribution_base_path_prefix_free" ();
"""

REMOVE_TRIGGER = r"""
DROP TRIGGER IF EXISTS "core_distribution_update_base_path_overlap_constraint" ON "core_distribution";
DROP TRIGGER IF EXISTS "core_distribution_insert_base_path_overlap_constraint" ON "core_distribution";
DROP FUNCTION IF EXISTS "check_core_distribution_base_path_prefix_free";
DROP FUNCTION IF EXISTS "path_prefixes";
"""


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0156_alter_contentartifact_relative_path_and_more'),
    ]

    operations = [
        migrations.RunSQL(sql=ADD_TRIGGER, reverse_sql=REMOVE_TRIGGER, elidable=False),
    ]
