# Generated by Django 5.2.15 on 2026-07-09 17:21

import django.db.models.deletion
import django_lifecycle.mixins
import pulpcore.app.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0156_migrationstatus"),
    ]

    operations = [
        migrations.CreateModel(
            name="DomainMove",
            fields=[
                (
                    "pulp_id",
                    models.UUIDField(
                        default=pulpcore.app.models.base.pulp_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("pulp_created", models.DateTimeField(auto_now_add=True)),
                ("pulp_last_updated", models.DateTimeField(auto_now=True, null=True)),
                ("from_alias", models.SlugField()),
                ("to_alias", models.SlugField()),
                ("started_at", models.DateTimeField()),
                ("cutover_at", models.DateTimeField(null=True)),
                ("monitoring_until", models.DateTimeField(null=True)),
                ("cleaned_up_at", models.DateTimeField(null=True)),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cleaned_up", "Cleaned Up"),
                        ],
                        default="in_progress",
                    ),
                ),
                ("error", models.TextField(null=True)),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moves",
                        to="core.domain",
                    ),
                ),
            ],
            options={
                "ordering": ["-pulp_created"],
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
