# Generated by Django 5.2.15 on 2026-08-26

import django.db.models.deletion
from django.db import migrations, models

import pulpcore.app.models.access_policy


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0157_distribution_base_path_constraint"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnvVarHeaderContentGuard",
            fields=[
                (
                    "contentguard_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.contentguard",
                    ),
                ),
                ("header_name", models.TextField()),
                ("env_var", models.TextField()),
            ],
            options={
                "permissions": (
                    (
                        "manage_roles_envvarheadercontentguard",
                        "Can manage role assignments on EnvVar Header content guard",
                    ),
                ),
                "default_related_name": "%(app_label)s_%(model_name)s",
            },
            bases=("core.contentguard", pulpcore.app.models.access_policy.AutoAddObjPermsMixin),
        ),
    ]
