# Generated by Django 5.2.15 on 2026-09-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0158_domain_default_content_guard'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations = [
                migrations.RunSQL(
                    # These instructions are idempotent and only effective on the timeline with
                    # the 3.117.0 migrations properly applied.
                    sql="""
                    ALTER TABLE "core_contentartifact" ALTER COLUMN "relative_path" TYPE text;
                    ALTER TABLE "core_publishedartifact" ALTER COLUMN "relative_path" TYPE text;
                    ALTER TABLE "core_publishedmetadata" ALTER COLUMN "relative_path" TYPE text;
                    """,
                    reverse_sql="",
                ),
            ],
            state_operations = [
                migrations.AlterField(
                    model_name='contentartifact',
                    name='relative_path',
                    field=models.TextField(),
                ),
                migrations.AlterField(
                    model_name='publishedartifact',
                    name='relative_path',
                    field=models.TextField(),
                ),
                migrations.AlterField(
                    model_name='publishedmetadata',
                    name='relative_path',
                    field=models.TextField(),
                ),
            ],
        )
    ]
