# Generated by Django 5.2.15 on 2026-09-03 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0158_domain_default_content_guard'),
    ]

    operations = [
        migrations.RunSQL(
            # This operation does nothing in the corrected timeline.
            # But if you are upgrading from 3.117.0 you'll need this.
            # It is idempotent.
            # This needs to be plain SQL, since Django would see no change and not do it.
            sql="ALTER TABLE core_contentartifact ALTER COLUMN relative_path DROP NOT NULL;",
            reverse_sql="",
            elidable=True,
        ),
    ]
