# Generated by Django 5.2.15 on 2026-09-04 08:27

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('core', '0160_AFTERMATH_OF_0156_content_artifact'),
    ]

    operations = [
        # Intentionally empty.
        # The operations one would expect here needed to be added before the triggers were
        # installed. Leaving this here as an empty migration for this message.
        # Also this might be a good place if we needed to inject some instructions into weird
        # migration timelines later.
    ]
