# Generated by Django 5.2.15 on 2026-09-04 08:27

import pulpcore.app.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    # This migration may run for a long time, but it does not perform in a transaction.
    # And it therefore needs to take extra care about partially validated check constraints.
    # This migration should not result in any database change if the 3.117.0 timeline was taken.

    atomic = False

    dependencies = [
        ('core', '0161_AFTERMATH_OF_0156_distribution'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            -- This is a weird way to fake "ADD CONSTRAINT IF NOT EXISTS".
            -- Needed because neither ADD nor VALIDATE CONSTRAINT have "IF (NOT) EXISTS".
            ALTER TABLE "core_publishedartifact" ADD CONSTRAINT "temp_relative_path_check_2" CHECK ('/' || "relative_path" || '/' !~ '[\n\r\s\t\?#]|(/\.{0,2}/)') NOT VALID;
            ALTER TABLE "core_publishedartifact" DROP CONSTRAINT IF EXISTS "temp_relative_path_check";
            ALTER TABLE "core_publishedartifact" RENAME CONSTRAINT "temp_relative_path_check_2" TO "temp_relative_path_check";
            --

            ALTER TABLE "core_publishedartifact" VALIDATE CONSTRAINT "temp_relative_path_check";
            """,
            reverse_sql="""
            """,
            elidable=True,
        ),
        migrations.AlterField(
            model_name='publishedartifact',
            name='relative_path',
            field=pulpcore.app.models.fields.RelativePathField(),
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE "core_publishedartifact" DROP CONSTRAINT IF EXISTS "temp_relative_path_check";
            """,
            reverse_sql="""
            """,
            elidable=True,
        ),
    ]
