#!/bin/bash

# WARNING: DO NOT EDIT!
#
# This file was generated by plugin_template, and is managed by it. Please use
# './plugin-template --github pulpcore' to update this file.
#
# For more info visit https://github.com/pulp/plugin_template

# make sure this script runs at the repo root
cd "$(dirname "$(realpath -e "$0")")"/../..

set -u

if [ $# -gt 0 ]; then
  MATCHES=$(grep -n "_(f" "$@" 2>/dev/null || true)
else
  # fallback to original behavior if no files are provided
  set -v
  MATCHES=$(grep -n -r --include \*.py "_(f")
fi

if [ -n "$MATCHES" ]; then
  printf "\nERROR: Detected mix of f-strings and gettext:\n"
  echo "$MATCHES"
  exit 1
fi
